server.port: 8081

# Database configuration
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/book_review_searcher
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  show-sql: true
  generate-ddl: true
  hibernate.ddl-auto: update

jwt:
    secret-key: jung9928_book_review_app_2024.secret_key
    # 30 days
    token.expired-time-ms: 2592000000

    live:
#      atk: 1800000      # 30분
      atk: 300000        # 5분
      rtk: 604800000     # 7일


spring.redis:
  pool:
    min-idle: 0
    max-idle: 8
    max-active: 8

spring.data:
  redis:
    port: 6379
    host: localhost

spring.mail:
  host: smtp.naver.com              # smtp 서버 주소
  port: 587                         # IMAP/SMTP 설정
  username:
  password:
  properties:
    mail:
      smtp:
        auth: true                  # smtp 서버 인증이 필요한 경우 true로 지정
        starttls:                   # smtp 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true 설정. TLS : 데이터 암호화 전송 프로토콜
          enable: true