server.port: 8081

# Database configuration
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/book_review_searcher
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  show-sql: true
  generate-ddl: true
  hibernate.ddl-auto: update

jwt:
    secret-key: jung9928_book_review_app_2024.secret_key
    # 30 days
    token.expired-time-ms: 2592000000

    live:
      atk: 60000
      rtk: 300000


spring:
  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8

  data:
    redis:
      port: 6379
      host: localhost